resources:
  - url: http://127.0.0.1:5000/thermostat-dark-card.js
    type: module
views:
  - cards:
      - type: custom:thermostat-dark-card
        name: Living
        entity: climate.test
        test_gui: true